from typing import Protocol

from domain.entities.performative_goal import PerformativeGoal
from domain.entities.system_map import SystemNode, SystemEdge, SystemMap
from domain.entities.roadmap import TransitionRoadmap
from domain.entities.cycle import SiDCycle


class GoalRepository(Protocol):
    def find_all(self) -> list[PerformativeGoal]: ...
    def find_by_id(self, goal_id: str) -> PerformativeGoal | None: ...
    def find_by_level(self, level: str) -> list[PerformativeGoal]: ...
    def save(self, goal: PerformativeGoal) -> None: ...


class SystemMapRepository(Protocol):
    def find_all_maps(self) -> list[SystemMap]: ...
    def find_map_by_id(self, map_id: str) -> SystemMap | None: ...
    def find_all_nodes(self) -> list[SystemNode]: ...
    def find_all_edges(self) -> list[SystemEdge]: ...
    def save_map(self, system_map: SystemMap) -> None: ...
    def save_node(self, node: SystemNode) -> None: ...
    def save_edge(self, edge: SystemEdge) -> None: ...


class RoadmapRepository(Protocol):
    def find_by_id(self, roadmap_id: str) -> TransitionRoadmap | None: ...
    def save(self, roadmap: TransitionRoadmap) -> None: ...


class CycleRepository(Protocol):
    def find_all(self) -> list[SiDCycle]: ...
    def find_by_cycle_number(self, cycle_number: int) -> SiDCycle | None: ...
    def save(self, cycle: SiDCycle) -> None: ...
