from typing import Protocol

from domain.entities.performative_goal import PerformativeGoal
from domain.entities.system_map import SystemNode, SystemEdge
from domain.entities.roadmap import TransitionRoadmap


class GoalRepository(Protocol):
    def find_all(self) -> list[PerformativeGoal]: ...
    def find_by_id(self, goal_id: str) -> PerformativeGoal | None: ...
    def save(self, goal: PerformativeGoal) -> None: ...


class SystemMapRepository(Protocol):
    def find_all_nodes(self) -> list[SystemNode]: ...
    def find_all_edges(self) -> list[SystemEdge]: ...
    def save_node(self, node: SystemNode) -> None: ...
    def save_edge(self, edge: SystemEdge) -> None: ...


class RoadmapRepository(Protocol):
    def find_by_id(self, roadmap_id: str) -> TransitionRoadmap | None: ...
    def save(self, roadmap: TransitionRoadmap) -> None: ...
